### PR TITLE
stages/authenticator_validate: remember

### PR DESCRIPTION
**Pull request by BeryJu**
Add option only validate MFA when device has not been used in x time

### CODE REVIEW

**Comment by Matchlighter** [comment]
@BeryJu It looks like the last 2FA verification timestamp is being stored in the DB (as the `last_t` column)? It should be stored in the/a cookie so that it is scoped to a single client/browser. Otherwise it creates a security implication that if the true user logs in and completes MFA, a malicious device has an opportunity to login as that user without being impeded by 2FA.

**Comment by BeryJu** [comment]
@Matchlighter you raise a good point, it would have to be stored in a separate, signed/encrypted cookie that lasts longer than the session (maybe no expiry at all?), but yes, the way you've described it is what would currently happen. I'll add a note to the docs to make this clear to people configuring it, since the above solution is not an easy fix

**Comment by BeryJu** [comment]
Actually we could set a cookie with an expiry of the configure threshold in the stage, save which device the user used to authenticate that session and then simply check for it's existence (and check the device belongs to the current user and the current stage, etc), but that should be pretty simple

**Comment by BeryJu** [comment]
Yeah true the expiration would also be saved in the cookie, or alternatively the timestamp of when the verification was done, which would make changing of the threshold easier

**Pull request merged**
