### PR TITLE
Update translation.md

### PR DESCRIPTION
**Pull request by ghost**
Instructions were unclear; took a while for me to figure it out.

# Details
* **Does this resolve an issue?**
Resolves #

### New Features
* Adds feature which does x, y, and z.

### Breaking Changes
* Adds breaking change which causes \<issue\>.

## Additional
Any further notes or comments you want to make.

### CODE REVIEW

**Comment by BeryJu** [comment]
Hi, thanks for the PR! The translation setup *should* work (in theory) without having to install lingui and babel in your home directory, running `npm i` in the `/web/` folder should be enough, but I'll do some testing.

**Comment by BeryJu** [comment]
@vrifox Try this:

```
In the root of the cloned repository, run `make gen-web` to generate the API Client used by the webinterface.

Afterwards, run `npm i` in the `/web` folder to install all dependencies.
```

**Comment by vrifox** [comment]
If I run `make gen-web` in the root directory, it tries to run a docker container. Is that really necessary to translate the Frontend? 🤔

Thanks for the quick response @BeryJu. 🙂

**Comment by BeryJu** [comment]
So it indirectly does. When you run npm i to install dependencies, it complains about the missing API client since that's a direct dependency, and of course you also need the API client to test your changes. Although it should be possible to generate a PO file without doing all of that, I agree.

**Comment by BeryJu** [comment]
Alternatively you can also use transifex: https://www.transifex.com/beryjuorg/authentik/dashboard

**Comment by vrifox** [comment]
Thank you for the link. I’ve tried Transifex, but it does not work for me. I simply can’t edit anything, do you have to authorize me?
And should I close this pull request or are you doing it? I’m not firm with Github. ^^

**Comment by BeryJu** [comment]
Yeah so I have to authorize people to contribute on transifex but it doesn't send me an email notification when people request access so I do miss it quite a lot. I've just accepted the request to join, thanks for your help already! I'll close the PR for now since theres now instructions to do it fully locally, but yeah transifex is probably the easier way.

**Pull request closed without merging**
