### PR TITLE
outposts: support json patch for Kubernetes

### LINKED ISSUE #5908: Support customizing kubernetes objects created by managed outposts
**Is your feature request related to a problem? Please describe.**
On my cluster, I have both local, on premises nodes as well as nodes running in cloud instances. The outpost deployments generated by the kubernetes integration does not support specifying a nodeSelector or affinity options.

Node placement is more of a concern when dealing with outposts that may need to be exposed outside the cluster, such as RADIUS or LDAP outposts, and where you ideally want their externalTrafficPolicy to be Local to preserve the requesting source IPs.

It might also be a concern if you're literally using the proxy outpost to... proxy... instead of using an external reverse proxy to forward-auth.

**Describe the solution you'd like**
Either allowing a nodeSelector or affinity to be specified as part of the outpost configuration.

**Describe alternatives you've considered**
Supporting a more generic jsonpatch/strategicMergePath approach to patching it.

**Additional context**

### PR DESCRIPTION
**Pull request by ChandonPierre**
## Details

-   **Does this resolve an issue?**
    Resolves #5908 

### New Features

-   Adds support to apply an [RFC 6902](https://datatracker.ietf.org/doc/html/rfc6902) compliant JSON patch to Kubernetes outpost deployments via `kubernetes_json_patch` outpost config option. 
- Provides the ability to override the refrence deployment spec with `nodeAffinity`, `tolerations`, `resources`, etc
- Changes to the JSON patch are reconciled, since a provided patch is compared against the current V1Deployment spec

### Breaking Changes

-   Adds breaking change which causes \<issue\>.

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [x] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)
-   [x] The translation files have been updated (`make i18n-extract`)

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by BeryJu** [comment]
@ChandonPierre thanks for the PR! I made quite a few changes with https://github.com/goauthentik/authentik/pull/6319/commits/b0617d026c48d96ae16009158b223874632bb95f (what was supposed to be a small commit), lmk if you'd change anything about that commit

**Review by BeryJu — APPROVED** [review]

**Comment by los93sol** [comment]
Is there an example of using this in the web ui anywhere?  I've been trying to get it to work but cannot seem to get any patches to apply

**Comment by los93sol** [comment]
Thanks, that appears to work, is it possible to patch the service though?  It seems to just not create the service when I do anything to it in the patches

**Comment by los93sol** [comment]
Wierd, I'm trying to use this...

kubernetes_json_patches:
  service:
    - op: add
      path: /spec
      value:
        loadBalancerIP: 192.168.80.101

and it isn't showing anything in the logs on either the worker or server, but the service never gets created when I reference it that way

**Comment by los93sol** [comment]
Yes, I changed it to LoadBalancer and am attempting to configure the metallb annotation to allow sharing of the ip, but so far no luck getting the patch to apply

**Comment by los93sol** [comment]
kubernetes_json_patches:  
  service:  
    - op: add  
      path: /metadata/annotations/loadBalancerIPs  
      value: 192.168.80.101

Here's another attempt that seems to fail to create it, but I still am not seeing anything in the logs

**Pull request merged**
