### PR TITLE
root: Improve Redis configuration

### LINKED ISSUE #1285: Support redis sentinel
**Is your feature request related to a problem? Please describe.**
I would like to deploy authentik on kubernetes with a separately configured distributed redis setup.
Typically a distributed redis is setup using [redis sentinel](https://redis.io/topics/sentinel).
As far as I know authentik currently does not support redis sentinel.

**Describe the solution you'd like**
I'd like, that authentik allows configuring redis sentinels and uses them.

**Describe alternatives you've considered**
Using a non-distributed redis installation, but then the redis is not as fail-save.

**Additional context**
For the django part: The `django-redis` libary recently added support for this. [docs](https://github.com/jazzband/django-redis#use-the-sentinel-connection-factory)
Celery also has support. [docs](https://docs.celeryproject.org/en/latest/getting-started/backends-and-brokers/redis.html?highlight=sentinel#configuration)
The python `redis` libary, too. [docs](https://github.com/andymccurdy/redis-py#sentinel-support)
Same for `go-redis`. [docs](https://pkg.go.dev/github.com/go-redis/redis/v8#NewFailoverClient)

### LINKED ISSUE #5077: Redis (Unix) Socket?
**Describe your question/**
Is it possible to run an authentik docker container (server and worker) with a redis unix socket rather than tcp?
Directly overwriting redis variables via user_settings.py doesn't appear to modify anything despite @BeryJu suggesting in [pull request #4036](https://github.com/goauthentik/authentik/pull/4036) it should be viable.

**Relevant infos**
Docker compose:
version: '3.4'

services:
  server:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    command: server
    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${PG_HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
      AUTHENTIK_LISTEN__HTTP: ${AUTHENTIK_LISTEN__HTTP}
      AUTHENTIK_LISTEN__HTTPS: ${AUTHENTIK_LISTEN__HTTPS}
    volumes:
      - ./media:/media
      - ./custom-templates:/templates
      - /run/redis/redis-server.sock:/run/redis/redis-server.sock
      - /var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432
      - ./user_settings.py:/data/user_settings.py
    ports:
      - "${AUTHENTIK_PORT_HTTP}:${AUTHENTIK_PORT_HTTP}"
      - "${AUTHENTIK_PORT_HTTPS}:${AUTHENTIK_PORT_HTTPS}"
  worker:
    image: ${AUTHENTIK_IMAGE:-ghcr.io/goauthentik/server}:latest
    restart: unless-stopped
    command: worker
    environment:
      AUTHENTIK_POSTGRESQL__HOST: ${PG_HOST}
      AUTHENTIK_POSTGRESQL__USER: ${PG_USER}
      AUTHENTIK_POSTGRESQL__NAME: ${PG_NAME}
      AUTHENTIK_POSTGRESQL__PASSWORD: ${PG_PASS}
      AUTHENTIK_REDIS__HOST: ${REDIS_HOST}
      AUTHENTIK_SECRET_KEY: ${AUTHENTIK_SECRET_KEY}
    user: authentik
    volumes:
      - ./media:/media
      - ./certs:/certs
      - ./custom-templates:/templates
      - /run/docker.sock:/var/run/docker.sock
      - /run/redis/redis-server.sock:/run/redis/redis-server.sock
      - /var/run/postgresql/.s.PGSQL.5432:/var/run/postgresql/.s.PGSQL.5432
      - ./user_settings.py:/data/user_settings.py

I didn't include the definition for ${REDIS_HOST} as sockets cannot be passed via environmental variables per [pull 4036](https://github.com/goauthentik/authentik/pull/4036).

**Logs**
DBG undefined | event=Loaded config logger=authentik.lib.config timestamp=1679734632.5913134 file=/authentik/lib/default.yml 
DBG undefined | event=Loaded environment variables logger=authentik.lib.config timestamp=1679734632.5915806 count=7 
INF undefined | event=Starting authentik bootstrap logger=authentik.lib.config timestamp=1679734632.59165 
INF undefined | event=PostgreSQL connection successful logger=authentik.lib.config timestamp=1679734632.5988 
INF undefined | event=Redis Connection failed, retrying... (Error 99 connecting to localhost:6379. Cannot assign requested address.) logger=authentik.lib.config timestamp=1679734633.600902 redis_url=redis://:@localhost:6379/0 

**Version and Deployment (please complete the following information):**
 - authentik version: 2023.3
 - Deployment: docker-compose

**Additional context**
docker exec -it authentik-stack-server-1 bash
authentik@283a42f97c09:/$ cd /data
authentik@283a42f97c09:/data$ ls -la
total 27
drwxr-xr-x  2 root root           3 Mar 25 08:24 .
drwxr-xr-x 33 root root          39 Mar 25 08:24 ..
-rw-rw-r--  1 1022 _runit-log 16463 Mar 25 08:45 user_settings.py
authentik@283a42f97c09:/data$ cat user_settings.py | grep redis
REDIS_PROTOCOL_PREFIX = "redis://"
if CONFIG.y_bool("redis.tls", False):
    REDIS_PROTOCOL_PREFIX = "rediss://"
    REDIS_CELERY_TLS_REQUIREMENTS = f"?ssl_cert_reqs={CONFIG.y('redis.tls_reqs')}"
_redis_url = (
    f"{quote_plus(CONFIG.y('redis.password'))}@{quote_plus(CONFIG.y('redis.host'))}:"
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": 'unix://run/redis/redis-server.sock',
        "TIMEOUT": int(CONFIG.y("redis.cache_timeout", 300)),
        "OPTIONS": {"CLIENT_CLASS": "django_redis.client.DefaultClient"},
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": 'unix://run/redis/redis-server.sock',
CELERY_BROKER_URL = 'redis+socket:///run/redis/redis-server.sock'
CELERY_RESULT_BACKEND = 'redis+socket:///run/redis/redis-server.sock'
    "redis": "WARNING",
authentik@283a42f97c09:/data$

### PR DESCRIPTION
**Pull request by PKizzle**
# Details

Resolves #5077, resolves #1285

- Redis URL parser adapted from [gitea project](https://github.com/go-gitea/gitea) for Go implementation
- Redisstore adapted from [BoxGo](https://github.com/boxgo/redisstore) for Go implementation

### New Features

- **Uses one URL for configuration of Redis (shared between Go and Python)**
- The Python URL parser has been created in a way to resemble the Go version
- By default uses Redis for broker, channel, backend (current state), but also allows for custom options
- Moves part of configuration currently under redis category into new dedicated sections -> split into https://github.com/goauthentik/authentik/pull/7097
- Adds deprecation check to config parser to allow for easy transition between old and new configuration scheme
- Old Redis configuration env vars are automatically converted to a Redis config URL if no Redis config URL has been configured otherwise they are ignored
- The new Redis URL allows environment variables to be included in bash style ${VAR}

### Breaking Changes

- ~~Several new Redis configuration env vars are no longer supported as everything is handled using the URL~~

### Additional information

- Newly supported Redis configurations are only available using the new Redis config URL environment variable
- The Redis config URL requires special characters in parameters to be URL encoded (e.g. username, password)

## Todo

- [x] Breaking change shall be removed by automatically converting current config options to URL
- [x] Tests are currently missing
- [x] Find a way to fix https://github.com/django/channels_redis/issues/345
- [x] Not tested for unix socket connection
- [x] Not working for Redis cluster -> new PR required
- [x] Add documentation on how the new Redis config URL works
- [x] Split PR into ~~Dockerfile adjustments,~~ env variable deprecation logic and Redis URL parsing -> does not make sense

### CODE REVIEW

**Comment by BeryJu** [comment]
Thanks for the great PR @PKizzle! Let me know when it's ready to be reviewed (allthough maybe some of the smaller changes we can merge as a separate PR to keep this a bit more streamlined)

Ideally there would still be options without a URL as only having a URL makes it harder to set passwords with characters that need to be escaped in an environment like K8s, allthough Helm probably has ways to URL encode passwords

**Comment by PKizzle** [comment]
@BeryJu What changes would you split of this PR?

**Comment by PKizzle** [comment]
@BeryJu Splitting up the PR now does not make much sense as the Docker adjustments have been removed in favor of a different PR. Also, the config restructuring and the deprecation logic only make sense in the context of this PR. It would require quite some time to get all tests to pass if separated.

Redis cluster support needs to be done in a different PR as it requires a lot of additions to the middleware. Basically that means to extend Celery's dependencies with that functionality as the respective projects have not seen any progress in that direction. One might argue that instead of maintaining the necessary source code here it should be implemented in the respective project's repos.

**Comment by PKizzle** [comment]
There are no tests for the added middleware as more discussion is needed whether Redis sentinel and unix socket configurations shall be tested e2e using the GitHub actions.

**Comment by gcarrarom** [comment]
@PKizzle Any reason to close this PR? Are we still looking at using Redis Cluster?

**Comment by PKizzle** [comment]
@gcarrarom I renamed the branch to better organise them locally and GitHub did not like that. The PR still lives on as https://github.com/goauthentik/authentik/pull/7118. It also includes Redis Cluster support. Please test it thoroughly and report any bugs.

**Pull request closed without merging**
