### PR TITLE
enterprise: fix license check not using the proper JWT algorithm

### PR DESCRIPTION
**Pull request by rissson**
## Details

-   **Does this resolve an issue?**
    Resolves #

Little typo 

### New Features

-   Adds feature which does x, y, and z.

### Breaking Changes

-   Adds breaking change which causes \<issue\>.

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Review by BeryJu — APPROVED** [review]
ES521 is actually a valid algorithm too

**Comment by rissson** [comment]
> ES521 is actually a valid algorithm too

For JWTs? I can't find it in RFC 7518, neither as an option on https://jwt.io/

**Comment by rissson** [comment]
And pyjwt is also complaining about it:
```
Traceback (most recent call last):
  File "/authentik/enterprise/models.py", line 73, in validate
    decode(
  File "/usr/local/lib/python3.11/site-packages/jwt/api_jwt.py", line 210, in decode
    decoded = self.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jwt/api_jwt.py", line 151, in decode_complete
    decoded = api_jws.decode_complete(
              ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/jwt/api_jws.py", line 209, in decode_complete
    self._verify_signature(signing_input, header, signature, key, algorithms)
  File "/usr/local/lib/python3.11/site-packages/jwt/api_jws.py", line 301, in _verify_signature
    raise InvalidAlgorithmError("The specified alg value is not allowed")
jwt.exceptions.InvalidAlgorithmError: The specified alg value is not allowed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<console>", line 1, in <module>
  File "/authentik/enterprise/models.py", line 81, in validate
    raise ValidationError("Unable to verify license")
rest_framework.exceptions.ValidationError: [ErrorDetail(string='Unable to verify license', code='invalid')]
```

**Comment by BeryJu** [comment]
> > ES521 is actually a valid algorithm too
> 
> For JWTs? I can't find it in RFC 7518, nor as an option on https://jwt.io/

https://github.com/jpadilla/pyjwt/blob/master/jwt/algorithms.py#L103

**Pull request merged**
