### PR TITLE
providers/proxy: rework redirect mechanism

### LINKED ISSUE #5603: Proxy provider incorrect redirect behaviour
**Describe the bug**
This bug manifests as a seemingly random-ish redirect after a page refresh when the proxy token has expired and the user is redirected back to the app from the proxy outpost that has just generated a new token.

To make it more clear - let's say we have a forward auth single application set up correctly and working - let's call the application The Echo Server: `https://echo.domain.tld`. We visit the Echo Server, idle for some time, and manage to wait enough so that the proxy token expires. When the Echo Servers sends a request to some kind of Echo Server's **resource (`https://echo.domain.tld/static/resource.json`)** AFTER the token expires (which fails because of the expired token) and THEN we refresh the current page (`https://echo.domain.tld/home`), we get redirected to authentik proxy outpost which in turns generates a new token and redirects the user back to the Echo Server - but when authentik eventually redirects the user back to the app the URL is **`https://echo.domain.tld/static/resource.json`** and not the original path from which the flow started `https://echo.domain.tld/home`.

**To Reproduce**

1. Have a working setup of a protected application with a proxy provider in Forward auth (single application) mode ("The Echo Server" described above)
2. In the app's proxy provider update the Token validity setting to a short duration, e.g. `seconds=30` for demonstration purposes
3. Go to the app (e.g. `https://echo.domain.tld/home`) and successfully authenticate/authorize.
4. Wait 30 seconds until the token expires
5. Open a developer console and simulate an artificial resource request of some kind: `fetch("https://echo.domain.tld/static/resource.json")` - the fetch fails because the token has expired. You can verify in the network tab that the fetch request gets redirected to the outpost and fails: `https://echo.domain.tld/outpost.goauthentik.io/start?rd=https%3A%2F%2Fecho.domain.tld%2Fstatic%2Fresource.json`.
6. Now refresh the page while still being at the same URL: `https://echo.domain.tld/home` - You can verify in the network tab that the refresh request gets redirected to the outpost _with correct redirect argument set_: `https://echo.domain.tld/outpost.goauthentik.io/start?rd=https%3A%2F%2Fecho.domain.tld%2Fhome`
7. You eventually get redirected back to the app's resource requested in step 5: `https://echo.domain.tld/static/resource.json`

**Expected behavior**
I would expect to be eventually redirected back to the `https://echo.domain.tld/home` page.

**Logs**

<details>
<summary>Logs</summary>

```
{"event":"/outpost.goauthentik.io/auth/nginx","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"0.343","scheme":"http","size":0,"status":200,"timestamp":"2023-05-14T22:28:10Z","user":"UserName","user_agent":"USER_AGENT"}
{"event":"/outpost.goauthentik.io/auth/nginx","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"0.930","scheme":"http","size":21,"status":401,"timestamp":"2023-05-14T22:29:07Z","user_agent":"USER_AGENT"}
{"event":"/outpost.goauthentik.io/start?rd=https%3A%2F%2Fecho.domain.tld%2Fstatic%2Fresource.json","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"1.123","scheme":"http","size":359,"status":302,"timestamp":"2023-05-14T22:29:07Z","user_agent":"USER_AGENT"}
{"event":"/outpost.goauthentik.io/auth/nginx","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"0.933","scheme":"http","size":21,"status":401,"timestamp":"2023-05-14T22:29:11Z","user_agent":"USER_AGENT"}
{"event":"/outpost.goauthentik.io/start?rd=https%3A%2F%2Fecho.domain.tld%2Fhome","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"1.319","scheme":"http","size":359,"status":302,"timestamp":"2023-05-14T22:29:11Z","user_agent":"USER_AGENT"}
{"auth_via": "session", "event": "/application/o/authorize/?client_id=ffffffffffffffffffffffffffffffff&redirect_uri=https%3A%2F%2Fecho.domain.tld%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=openid+profile+email+ak_proxy&state=NdC1Ol7jMCT8oS_P9oKDQ3J6gvnETS4eWUbMbo4DbRo", "host": "auth.domain.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "xxx.xxx.xxx.xxx", "request_id": "5b1ce3f63ab44b67ae482cd4eef3548d", "runtime": 74, "scheme": "https", "status": 302, "timestamp": "2023-05-14T22:29:11.311489", "user": "UserName", "user_agent": "USER_AGENT"}
{"auth_via": "session", "event": "/if/flow/default-provider-authorization-explicit-consent/?client_id=ffffffffffffffffffffffffffffffff&redirect_uri=https%3A%2F%2Fecho.domain.tld%2Foutpost.goauthentik.io%2Fcallback%3FX-authentik-auth-callback%3Dtrue&response_type=code&scope=openid+profile+email+ak_proxy&state=NdC1Ol7jMCT8oS_P9oKDQ3J6gvnETS4eWUbMbo4DbRo", "host": "auth.domain.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "xxx.xxx.xxx.xxx", "request_id": "9dabf88c7f7f40cb909a317c47132181", "runtime": 33, "scheme": "https", "status": 200, "timestamp": "2023-05-14T22:29:11.362915", "user": "UserName", "user_agent": "USER_AGENT"}
{"event":"/static/dist/poly.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"4.872","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:11Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/standalone/loading/vendor-320681c9.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"1.094","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/standalone/loading/api-f65fd993.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.742","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/standalone/loading/locale-en-f660cb3b.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.523","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/standalone/loading/index.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.438","scheme":"http","size":53898,"status":200,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/standalone/loading/index.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.196","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/FlowInterface-d33d9ac4.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"2.285","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/FlowInterface.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.127","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/locale-en-f660cb3b.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"1.856","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/vendor-cm-00a4719e.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"7.299","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/api-befd9628.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"13.889","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/assets/icons/icon_left_brand.svg","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.511","scheme":"http","size":4861,"status":200,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/if/flow/default-provider-authorization-explicit-consent/assets/fonts/RedHatText/RedHatText-Regular.woff2","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.523","scheme":"http","size":3768,"status":200,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/if/flow/default-provider-authorization-explicit-consent/assets/fonts/RedHatDisplay/RedHatDisplay-Medium.woff2","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"0.521","scheme":"http","size":28661,"status":200,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/vendor-25865c6e.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"45.016","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"event":"/static/dist/flow/FlowInterface-d33d9ac4.js.map","host":"auth.domain.tld","level":"info","logger":"authentik.router","method":"GET","remote":"xxx.xxx.xxx.xxx","runtime":"1.530","scheme":"http","size":0,"status":304,"timestamp":"2023-05-14T22:29:12Z","user_agent":"USER_AGENT"}
{"auth_via": "session", "event": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=client_id%3Dffffffffffffffffffffffffffffffff%26redirect_uri%3Dhttps%253A%252F%252Fecho.domain.tld%252Foutpost.goauthentik.io%252Fcallback%253FX-authentik-auth-callback%253Dtrue%26response_type%3Dcode%26scope%3Dopenid%2Bprofile%2Bemail%2Bak_proxy%26state%3DNdC1Ol7jMCT8oS_P9oKDQ3J6gvnETS4eWUbMbo4DbRo", "host": "auth.domain.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "xxx.xxx.xxx.xxx", "request_id": "bccf832ab85840c7899bef18fb76899e", "runtime": 233, "scheme": "https", "status": 302, "timestamp": "2023-05-14T22:29:12.466727", "user": "UserName", "user_agent": "USER_AGENT"}
{"action": "authorize_application", "auth_via": "session", "client_ip": "xxx.xxx.xxx.xxx", "context": {"authorized_application": {"app": "authentik_core", "model_name": "application", "name": "Echo server", "pk": "d208963c731d4cb282ae64397f731688"}, "flow": "a8c59e9e6fbc4e1d9a53365db1bf8704", "http_request": {"args": {"client_id": "ffffffffffffffffffffffffffffffff", "redirect_uri": "https://echo.domain.tld/outpost.goauthentik.io/callback?X-authentik-auth-callback=true", "response_type": "code", "scope": "openid profile email ak_proxy", "state": "NdC1Ol7jMCT8oS_P9oKDQ3J6gvnETS4eWUbMbo4DbRo"}, "method": "GET", "path": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/"}, "scopes": "openid profile email ak_proxy"}, "event": "Created Event", "host": "auth.domain.tld", "level": "info", "logger": "authentik.events.models", "pid": 24, "request_id": "15975e5a84894e668b1127b804d7b3d8", "timestamp": "2023-05-14T22:29:12.654030", "user": {"email": "email@example.com", "pk": 12, "username": "UserName"}}
{"auth_via": "session", "event": "Task published", "host": "auth.domain.tld", "level": "info", "logger": "authentik.root.celery", "pid": 24, "request_id": "15975e5a84894e668b1127b804d7b3d8", "task_id": "94594c44-1672-4710-b659-96c22b3580f6", "task_name": "authentik.events.tasks.event_notification_handler", "timestamp": "2023-05-14T22:29:12.678197"}
{"auth_via": "session", "event": "/api/v3/flows/executor/default-provider-authorization-explicit-consent/?query=client_id%3Dffffffffffffffffffffffffffffffff%26redirect_uri%3Dhttps%253A%252F%252Fecho.domain.tld%252Foutpost.goauthentik.io%252Fcallback%253FX-authentik-auth-callback%253Dtrue%26response_type%3Dcode%26scope%3Dopenid%2Bprofile%2Bemail%2Bak_proxy%26state%3DNdC1Ol7jMCT8oS_P9oKDQ3J6gvnETS4eWUbMbo4DbRo", "host": "auth.domain.tld", "level": "info", "logger": "authentik.asgi", "method": "GET", "pid": 24, "remote": "xxx.xxx.xxx.xxx", "request_id": "15975e5a84894e668b1127b804d7b3d8", "runtime": 113, "scheme": "https", "status": 200, "timestamp": "2023-05-14T22:29:12.709587", "user": "UserName", "user_agent": "USER_AGENT"}
{"auth_via": "unauthenticated", "event": "/-/health/ready/", "host": "localhost:9000", "level": "info", "logger": "authentik.asgi", "method": "HEAD", "pid": 24, "remote": "127.0.0.1", "request_id": "5cc814939c734f85ab612559d77ee914", "runtime": 18, "scheme": "http", "status": 204, "timestamp": "2023-05-14T22:29:12.845074", "user": "", "user_agent": "goauthentik.io lifecycle Healthcheck"}
{"auth_via": "unauthenticated", "event": "/application/o/token/", "host": "auth.domain.tld", "level": "info", "logger": "authentik.asgi", "method": "POST", "pid": 10514, "remote": "127.0.0.1", "request_id": "dbc6b792cbc247dd8a879fb0dd8ec8f4", "runtime": 54, "scheme": "https", "status": 200, "timestamp": "2023-05-14T22:29:13.024719", "user": "", "user_agent": "goauthentik.io/outpost/2023.4.1 (provider=Echo server proxy)"}
{"event":"/outpost.goauthentik.io/callback?X-authentik-auth-callback=true&code=942d95ae2232466aa67a89e8bc8f826f&state=NdC1Ol7jMCT8oS_P9oKDQ3J6gvnETS4eWUbMbo4DbRo","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"57.903","scheme":"http","size":68,"status":302,"timestamp":"2023-05-14T22:29:13Z","user_agent":"USER_AGENT"}
{"event":"/outpost.goauthentik.io/auth/nginx","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"0.308","scheme":"http","size":0,"status":200,"timestamp":"2023-05-14T22:29:13Z","user":"UserName","user_agent":"USER_AGENT"}
{"event":"/outpost.goauthentik.io/auth/nginx","host":"echo.domain.tld","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"Echo server proxy","remote":"xxx.xxx.xxx.xxx","runtime":"0.486","scheme":"http","size":0,"status":200,"timestamp":"2023-05-14T22:29:13Z","user":"UserName","user_agent":"USER_AGENT"}
```

</details>

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.4.1
-   Deployment: docker-compose

**Additional context**
Using nginx reverse proxy.

There are also users on Discord experiencing the same behaviour: https://discord.com/channels/809154715984199690/809154716507963434/1101389383300567060

### LINKED ISSUE #6886: Proxy provider random incorrect redirects
This is a summarising issue for #4732, #5603, #4166, #6253 and a bunch of other ones

The gist of the issue is that the proxy provider will occasionally (depending on application it happens more or less often) redirect to the incorrect URL. As far as I know this only happens with the forward_auth and forward_auth domain mode

This is caused by the provider saving the final redirect URL in the session whenever accessing the forward_auth url without a session, so that the final redirect can be done correctly. When using a website/PWA that loads many things at once, requests for resources can be sent at the same time and overwrite that session value, causing the final redirect to point to a JS/CSS file, or with the forward_auth domain mode even to point to a different domain.

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

closes #6886
closes #5603

instead of relying on `?rd=` being set and carried forward (which doesn't happen due to OAuth redirect URLs) and using `oauth_redirect` in the session (which can be overwritten by parallel requests and mainly leads to #6886)

this PR changes the logic to encode the redirect URL (after being validated) into the `state` param (turning the `state` param into a signed JWT which also contains the random secret), and then using the same state when returning to redirect the user in the end.

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by hdlineage** [comment]
Will this patch be included in the next release?

**Comment by BeryJu** [comment]
as there hasn't been enough testing with this for all the possible setup options (we've tested it with proxy (single) and forward auth with nginx and envoy), we won't be including this in the next 2024.4 bugfix release. However in this case it should be possible to use the beta outpost image with the 2024.4 release to test this change.

**Comment by CrossEyeORG** [comment]
Hey BeryJu, do you think this fix will make it into any 2024.4 version or get pushed to 2024.6? Thanks again for a great product!

**Comment by plsnotracking** [comment]
Hi @BeryJu I picked up the latest change, and am consistently running into this, not sure if I'm not getting it right or if this is the problem, is there an easy way to discern that? Thank you.

`Helm` deployment: `2024.6.1`

The one odd thing I saw on my Authentik dashboard was under `System > Outpost Integrations > Local Kubernetes Cluster` was `Unhealthy` but on editing and saving it'll temporary be happy, and fail again once page is refreshed. I have no idea exactly what is even unhealthy, since other Auth works fine except for Proxy.

Screenshot
Screenshot 2024-07-17 at 11 35 17 PM


Logs from `server` service:
```bash
{"event":"/outpost.goauthentik.io/auth/nginx","host":"app.enterprise.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"app","remote":"10.42.0.19","runtime":"4.71
6","scheme":"http","size":21,"status":401,"timestamp":"2024-07-18T07:25:47Z","user_agent":"Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0"}
{"auth_via": "unauthenticated", "domain_url": "auth.enterprise.com", "event": "/outpost.goauthentik.io/start?rd=https://app.enterprise.com/", "host": "auth.enterprise.com", "level": "info", "logger": "
authentik.asgi", "method": "GET", "pid": 46, "remote": "10.42.2.28", "request_id": "d1d62aa5e6e248b9a3fe6b723bd25285", "runtime": 4, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2024-07-
18T07:25:47.510619", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0"}
```

Logs from the `outpost` service:
```bash
{"event":"/outpost.goauthentik.io/auth/nginx","host":"app.enterprise.com","level":"info","logger":"authentik.outpost.proxyv2.application","method":"GET","name":"app","remote":"10.42.0.19","runtime":"4.71
6","scheme":"http","size":21,"status":401,"timestamp":"2024-07-18T07:25:47Z","user_agent":"Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0"}
{"auth_via": "unauthenticated", "domain_url": "app.enterprise.com", "event": "/outpost.goauthentik.io/start?rd=https://app.enterprise.com/", "host": "app.enterprise.com", "level": "info", "logger": "
authentik.asgi", "method": "GET", "pid": 46, "remote": "10.42.2.28", "request_id": "d1d62aa5e6e248b9a3fe6b723bd25285", "runtime": 4, "schema_name": "public", "scheme": "https", "status": 404, "timestamp": "2024-07-
18T07:25:47.510619", "user": "", "user_agent": "Mozilla/5.0 (Windows NT 10.0; rv:128.0) Gecko/20100101 Firefox/128.0"}
```

Here's what my `ingress` looks like
```yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: database
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/auth-url: http://ak-outpost-authentik-embedded-outpost.authentik.svc.cluster.local:9000/outpost.goauthentik.io/auth/nginx
    nginx.ingress.kubernetes.io/auth-signin: https://auth.enterprise.com/outpost.goauthentik.io/start?rd=$scheme://$http_host$request_uri
    nginx.ingress.kubernetes.io/auth-response-headers: Set-Cookie,X-authentik-username,X-authentik-groups,X-authentik-email,X-authentik-name,X-authentik-uid
    nginx.ingress.kubernetes.io/auth-snippet: |
      proxy_set_header X-Forwarded-Host $http_host;
      proxy_set_header X-Real-IP $remote_addr;  # Forward real client IP
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;  # Forward client IPs
      proxy_set_header X-Forwarded-Proto $scheme;  # Forward protocol (HTTP/HTTPS)
spec:
  rules:
  - host: app.enterprise.com
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: app
              port:
                number: 80

```

Results in

image


Please let me know if I can provide anymore data at all. Thanks.

**Pull request merged**
