### PR TITLE
website/integrations:  update vcenter integration docs

### PR DESCRIPTION
**Pull request by tanberry**
This PR updates the integration docs for VMWare VCenter.

If applicable

-   [x] The documentation has been updated
-   [x] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by tanberry** [comment]
Hello @Wouter0100 apologies, I think I mangled your commits somehow! I didn't see that you had made a commit to the PR, I only saw that there was a new file in the PR that I had not pushed, and thought I'd accidentally included it in my PR. So I removed it. Whah. Sorry about that. Can you take a look and repair the damage I did? We very much want your info added!

**Comment by Wouter0100** [comment]
My changes are already merged in, so should be fine!

https://github.com/goauthentik/authentik/pull/11702

**Comment by tanberry** [comment]
> My changes are already merged in, so should be fine!
> 
> #11702

OK good to hear, thanks for your patience.... for my learning, ummm... what exactly happened? I think you added your commits to this PR, then I foolishly removed the entire file from the PR... so how/when did your commits get merged? In a diff PR after you realized I was mangling things haha?

**Comment by Wouter0100** [comment]
I'm not sure what happened, but I didn't participate in this MR at all and haven't done anything specifically. It seems you somehow rebased my commit and put it in this branch. 

My changes were merged in #11702.

**Comment by tanberry** [comment]
> I'm not sure what happened, but I didn't participate in this MR at all and haven't done anything specifically. It seems you somehow rebased my commit and put it in this branch.
> 
> My changes were merged in #11702.

Ah, yes, that tracks... my rebase went awry. Thank you so much for both your contribution and for the explanation.

**Review by BeryJu — APPROVED** [review]

**Pull request merged**
