### PR TITLE
stages/email: Fix query parameters getting lost in Email links

### PR DESCRIPTION
**Pull request by roney492**
## Changes

Bugfix for https://github.com/goauthentik/authentik/issues/5149

### New Features

Fixes the bug with the broken email confirmation flow.

### Breaking Changes

None

### CODE REVIEW

**Comment by BeryJu** [comment]
Sorry @roney492 for taking so long to review this, just to clarify, this fixes an issue when using an OIDC-based application x, the user attempts to access application x and then enrolls and account with a flow that has an email stage, they are not redirected correctly to application x after confirming their email, right?

**Comment by roney492** [comment]
Hi @BeryJu,
Yes, that's correct!!

**Comment by BeryJu** [comment]
@roney492 I've done some testing with and without this PR and both worked correctly to keep the redirect URL. Could you post the Flow you're using for this?

**Comment by roney492** [comment]
Sure,
[enrollment_email.zip](https://github.com/goauthentik/authentik/files/11469677/enrollment_email.zip)

**Review by BeryJu — APPROVED** [review]

**Pull request merged**
