### PR TITLE
website/docs: Add OIDC auth integration with Nextcloud

### PR DESCRIPTION
**Pull request by astro-stan**
## Details

Adds detailed docs on setting up OIDC authentication with Nextcloud.  Includes tips and warnings against common pitfalls when setting up different configurations

## Checklist

-   [X] Local tests pass (`ak test authentik/`)
-   [X] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [X] The documentation has been updated
-   [X] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by sdimovv** [comment]
@BeryJu  can I get  a merge please :D

**Comment by sdimovv** [comment]
> Do you mind moving the OIDC section below the SAML one as it requires an additional nextcloud app to be installed? Also, let's add a quick sentence stating there are two different protocols that can be configured and linking to the specific section for each of them.

I can add the section about the different protocols, no problem. However, I think you misunderstood what is required for SAML. BOTH auth methods require the installation of an additional app in Nextcloud.  Both apps are  "official", that is provided by the Nexcloud devs. However, neither of them comes installed with vanilla Nextcloud install. So the "extra" requirements for both are the same.

**Review by rissson — APPROVED** [review]

**Comment by sdimovv** [comment]
@rissson 
Does this need anything else to get merged?

**Review by tanberry — CHANGES_REQUESTED** [review]
There's what I think is a typo that needs to be fixed... autorization --> authorization

**Comment by rissson** [comment]
Apart from the typo raised by Tana, all good for me

**Review by rissson — APPROVED** [review]

**Comment by sdimovv** [comment]
Typo fixed. Let me know if there are more. Otherwise this can be merged.

**Review by rissson — APPROVED** [review]

**Pull request merged**
