### PR TITLE
web/flows: fix device picker incorrect foreground color

### LINKED ISSUE #7990: Multiple authenticators does not display correctly (blank windows)
**Describe the bug**
If I select to include multiple authentication methods for a new user to choose from, such as TOTP and DUO, the newly created user will be presented with a blank windows at login page. The TOTP and DUO authentications options are still in the windows (the mouse cursor change to hand icon when I move over)

**To Reproduce**

0. Setup the Flow to enable TOTP and DUO authentication methods. Force the new user to select one at log-in page
1. Go to Directory > Users and create a new User called Test. Set the password for the User
2. Go to login page and login the new user with the credentials created in step 1
3. The windows showing 2 methods for the user to select is blank
4. Move your mouse to upper part: TOTP/ Lower part: DUO

**Expected behavior**
The two authentication options should be displayed correctly instead of a blank windows

**Screenshots**
Refer to the attached screenshot where the cursor show a hand icon, indicate that the options are still there, it was just not displayed properly

**Logs**
Output of docker-compose logs or kubectl logs respectively

**Version and Deployment (please complete the following information):**

-   authentik version: 2023.10.5
-   Deployment: docker compose

**Additional context**
If I select only 1 authentication method, either TOTP or DUO, it will show correctly

blank-auth-windows

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

closes #7990

---

## Checklist

-   [x] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by jamesngob** [comment]
Is this fix beta release or permanent fix?

**Comment by BeryJu** [comment]
it'll be included in 2023.8.6 and 2023.10.6 and also future releases

**Comment by jamesngob** [comment]
So the best way is to wait for 2023.10.6 then?
I am currently running 2023.10.5, and to upgrade, I just need to change the version to 2023.10.6 in the env file and then, run:

docker compose down 
docker compose up -d

or, do I have to run :

docker compose pull
docker compose up -d

Thank you

**Pull request merged**
