### PR TITLE
providers/saml: fix mismatched SAML SLO Urls

### PR DESCRIPTION
**Pull request by astro-stan**
# Details
According to the source code:

https://github.com/goauthentik/authentik/blob/b225f6f3ff6cbd5b0d69304c36ed30b81a45aa5d/authentik/providers/saml/urls.py#L25-L29

Notice no `/binding/`

### New Features
N/A

### Breaking Changes
N/A

## Additional
N/A

### CODE REVIEW

**Comment by BeryJu** [comment]
Good catch! The URL is actually supposed to have a `/binding/` part in the URL to match the SSO URLs (even though in the future I'd like to make it a single URL since these URLs are quite unwieldy but that can wait)

**Comment by sdimovv** [comment]
Thanks! Yea, a unified URL in the future would be even better. 

But regarding the current state of things - are you going to merge this? If you prefer, I can (or at least try to) submit a patch here that fixes the URL instead?

**Comment by BeryJu** [comment]
Yeah I'd prefer a PR to fix the URLs to be the same everywhere

**Comment by sdimovv** [comment]
Should be good now

**Pull request merged**
