### PR TITLE
Fixed the incorrect padding issue in apple.py

### PR DESCRIPTION
**Pull request by rizwan95**
Fixed the incorrect padding issue in apple.py by adding proper padding to the raw_payload.

# Details
* **Does this resolve an issue?**
Yes

### New Features
No

### Breaking Changes
No

## Additional
Fixed the incorrect padding issue in apple.py by adding proper padding to the raw_payload.

### CODE REVIEW

**Comment by BeryJu** [comment]
Is there any way to reproduce the issue this PR fixes?

Also after looking over the code again, it might be easier to just 

```python
from jwt import decode
[ .... ]

return decode(id_token)
``` instead of this

**Comment by rizwan95** [comment]
> Is there any way to reproduce the issue this PR fixes?
> 
> Also after looking over the code again, it might be easier to just
> 
> ```python
> from jwt import decode
> [ .... ]
> 
> return decode(id_token)
> ```
> 
> instead of this

Yes you can just configure an Apple source provider and sign in using it. In the last step, it will fail telling that "Incorrect padding" 

As you suggested, your solution is more elegant and makes much sense.

**Comment by BeryJu** [comment]
I don't remember which information is included in Apple's ID Token but I'd like to add some tests for this. Could you check with https://jwt.io/ which fields are included, and if there's anything personal besides Name?

**Comment by rizwan95** [comment]
> I don't remember which information is included in Apple's ID Token but I'd like to add some tests for this. Could you check with https://jwt.io/ which fields are included, and if there's anything personal besides Name?

Yes sure!

**Comment by rizwan95** [comment]
> I don't remember which information is included in Apple's ID Token but I'd like to add some tests for this. Could you check with https://jwt.io/ which fields are included, and if there's anything personal besides Name?
@BeryJu 
So here is the payload 

`{
  "iss": "https://appleid.apple.com",
  "aud": "<redacted>",
  "exp": 1636740983,
  "iat": 1636654583,
  "sub": "001786.d770f0696ea64f48a9c7b834bf536143.0359",
  "at_hash": "EKTUgiJwIUCtE65XXh0d_g",
  "email": "<redacted>",
  "email_verified": "true",
  "auth_time": 1636654580,
  "nonce_supported": true
}`

I have redacted the aud and email values

**Comment by BeryJu** [comment]
Alright, nothing special in there. I'll merge it with the `jwt` `decode()` function and we'll see about tests later

**Comment by rizwan95** [comment]
> Alright, nothing special in there. I'll merge it with the `jwt` `decode()` function and we'll see about tests later

Awesome!

**Comment by rizwan95** [comment]
@BeryJu 
I have also fixed an another issue which was causing incorrect encoding of the client_secret. 
The "sub" must be only the client id, so I have changed self.source.consumer_key to parts[0] in oauth/types/apple.py

**Comment by BeryJu** [comment]
> @BeryJu I have also fixed an another issue which was causing incorrect encoding of the client_secret. The "sub" must be only the client id, so I have changed self.source.consumer_key to parts[0] in oauth/types/apple.py

Cheers, can you add the `from jwt import decode` part? Then I'll merge the PR

**Comment by rizwan95** [comment]
> > @BeryJu I have also fixed an another issue which was causing incorrect encoding of the client_secret. The "sub" must be only the client id, so I have changed self.source.consumer_key to parts[0] in oauth/types/apple.py
> 
> Cheers, can you add the `from jwt import decode` part? Then I'll merge the PR

I tried to implement the decode part (I have very little knowledge about Python)
I am getting this error ```["<class 'jwt.exceptions.InvalidAlgorithmError'>", "InvalidAlgorithmError('The specified alg value is not allowed')```

for the code 
```decode(id_token,self.source.consumer_secret,algorithms=['ES256'])```

not sure what mistake I am doing

**Comment by BeryJu** [comment]
you can just do `return decode(id_token)` since we're not validating the JWT there anyways

**Comment by rizwan95** [comment]
> you can just do `return decode(id_token)` since we're not validating the JWT there anyways

I have added it. I suppose that should be enough.

**Pull request merged**
