### PR TITLE
providers/oauth2: fix refresh_token grant returning incorrect id_token

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

#4191

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by lsjostro** [comment]
Can we add proper integration tests for this?

**Comment by BeryJu** [comment]
@lsjostro do you have any suggestion on a client application that could be used for this? The OpenID compliance test didn't complain about this

I'll still merge this as-is for the time being so it can be included in 2024.4

**Comment by lsjostro** [comment]
I'm more searching for why this hasn't been noticed since the last fix 2 years ago? How can we prevent it will not happen in the future? issuing tokens valid for 30 days without letting users know is a big regression if you ask me. Writing e2e/integration tests and validating configuration vs token expire times etc would help? I dont think the compliance test would have caught this right? But yeah merge it and get it released asap is of course most important right now 👍🏻 and thanks for the quick fix!

**Comment by BeryJu** [comment]
@lsjostro I'm assuming that most applications don't use the `id_token`  part of a refresh_token grant as even the OIDC spec says this is optional, and hence it hasn't been noticed

**Comment by lsjostro** [comment]
that's not true, first app that pops up is the k8s api server?

**Comment by BeryJu** [comment]
sorry I meant from the apps I've used with the OIDC provider, I've not set up my K8s clusters to use the authentik OIDC provider yet

**Pull request merged**
