### PR TITLE
sources/oauth: add initial group sync

### LINKED ISSUE #6184: Support "groups" claim for OIDC OAuth Sources
Currently we dont support group import from OAuth OIDC sources

### PR DESCRIPTION
**Pull request by BeryJu**
## Details

Add the option to allow OIDC sources to sync groups

- Only for OIDC at the moment even though other source types may support it
- Requires inputting the claim for groups which requires a list of group names
 (Some sources like Azure AD return a list of UUIDs from the groups which we'd need additional logic to resolve)

closes #6184

---

## Checklist

-   [x] Local tests pass (`ak test authentik/`)
-   [x] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [x] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [x] The code has been formatted (`make web`)
-   [x] The translation files have been updated (`make i18n-extract`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by insunaa** [comment]
Looks like a great feature!
Will it be possible in the future to not just sync the group's name, but also the gid?

**Comment by kPKfQKhuz86** [comment]
hey, just bumping this one up. 

this is a deal breaker in my case and due to lack of this feature, I can't consider authentik a solution for my case at the moment. hoping this one is implemented soon, as otherwise I find authentik very intuitive to use!

**Comment by los93sol** [comment]
Will this be available soon?  Really need this for my use case

**Comment by BeryJu** [comment]
superseded by #8771

**Pull request closed without merging**
