### PR TITLE
web/flows: fix RedirectStage not detecting absolute URLs correctly

### LINKED ISSUE #5732: Portianer OAuth is broken after update.
**Describe the bug**
Can't Login in my Portianer instance.
'https://domain.me&scope=email%20openid%20profile&state=2a1078bf-bcc2-4300-a6b2-8a41ad511f4b' the error lies in 'domain.me&scope.' i think.

```
Uncaught (in promise) TypeError: Failed to construct 'URL': Invalid URL
    at n.value (RedirectStage.ts:61:21)
    at n.value (RedirectStage.ts:78:25)
    at n.update (lit-element.js:6:304)
    at n.performUpdate (reactive-element.js:6:4849)
    at n.scheduleUpdate (reactive-element.js:6:4496)
    at n._$Ej (reactive-element.js:6:4404)
```

**To Reproduce**
chrome_V572qvMzXq

**Expected behavior**
login normaly

**Screenshots**
My Portainer configuration
image

My Authentik configuration
image

**Logs**
`
INF action=login auth_via=unauthenticated client_ip=95.**.**.**.** context={"auth_method":"password","auth_method_args":{},"geo":{"city":"Mönch****","continent":"**","country":"**","lat":**.****,"long":*.*****},"http_request":{"args":{"next":"/application/o/authorize/?response_type=code&client_id=Bs4yO3vcPu21WZiwO4xnUZTaQh09bhjB1h0YXQt6&redirect_uri=https://domain.me&scope=email%20openid%20profile&state=2a1078bf-bcc2-4300-a6b2-8a41ad511f4b"},"method":"GET","path":"/api/v3/flows/executor/default-authentication-flow/"}} event=Created Event host=auth.domain.me logger=authentik.events.models pid=23 request_id=d8a8fc38478c403d8e4a4c21db2f0a6c timestamp=2023-05-24T03:34:26.192330 user={"email":"example@domain.me","pk":6,"username":"SmallPox"}
`
**Version and Deployment (please complete the following information):**

-   authentik version: [2023.5.1]
-   Deployment: Portainer BE 2.18.3

**Additional context**
I'm sorry, but I'm not sure exactly what's going on. Apparently, the URL is no longer correct. It's possible that Authentik is providing it incorrectly, even though everything is actually accurate.
The problem has only existed since I updated Authentik.
But in my opinion, something is missing after the domain extension. When I try to access the domain 'https://domain.me&scope=email%20openid%20profile&state=2a1078bf-bcc2-4300-a6b2-8a41ad511f4b' myself, I receive a 404 error. In my opinion, the error lies in 'domain.me&scope.'
I have also tried adding a forward slash in Authentik, so the request looked like this: 'domain.me/&scope,' but that didn't help either.
Maybe someone here can help me.

### PR DESCRIPTION
**Pull request by Saeverix**
## Details

-   **Does this resolve an issue?**
    Resolves #5732

### New Features

-   `getURL()` method in `RedirectStage.ts` now actually detects URLs

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)
-   [ ] The translation files have been updated (`make i18n-extract`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by Smallinger** [comment]
After I built my own Authentik image with the changes that @Saeverix made, I can confirm that all my OAuth connections are working properly. I am using:

- Portainer
- Proxmox
- Nginx Proxy Manager
- Nextcloud
- Gitea
- Coder
- Proxy Auth
- Element / Matrix
- Jellyfin
- 

Everything is working perfectly!

**Comment by Saeverix** [comment]
@Smallinger thanks for checking my changes and confirming that it works.

**Comment by BeryJu** [comment]
I've simplified the code a bit to use the native JS URL APIs and tested it with Portainer locally

**Comment by Saeverix** [comment]
@BeryJu that's also a nice change to prevent the `new URL()` to fail. Nice work!

**Review by BeryJu — APPROVED** [review]

**Pull request merged**
