### PR TITLE
web: Fix missing integrity fields in package-lock.json

### LINKED ISSUE #196: Validate missing integrity fields
**Is your feature request related to a problem? Please describe.**
Please describe the problem you are trying to solve.

I have lockfiles that occasionally get their integrity fields removed and npm installs the packages regardless (missing integrity is OK).  Also, I see you have a test that succeeds when there is a missing integrity: https://github.com/lirantal/lockfile-lint/blob/main/packages/lockfile-lint-api/__tests__/validators.integrityHashType.test.js#L68

**Describe the solution you'd like**

I want to be able to catch these issues and fix them, to guarantee that the packages we download are the same; this is in-line with this open npm-cli issue: https://github.com/npm/cli/issues/4460#issuecomment-1050025391

**Describe alternatives you've considered**

I would just write my own script to basically do the same parsing as this library :)

### PR DESCRIPTION
**Pull request by jvanbruegge**
## Details

Same issue as with https://github.com/goauthentik/authentik/pull/9419

There was a CI check for this, however https://github.com/goauthentik/authentik/pull/10157 removed the CI check, which made this issue possible again. `lint-lockfile` does not actually check that all packages are resolved: https://github.com/lirantal/lockfile-lint/issues/196

---

## Checklist

-   [ ] Local tests pass (`ak test authentik/`)
-   [ ] The code has been formatted (`make lint-fix`)

If an API change has been made

-   [ ] The API schema has been updated (`make gen-build`)

If changes to the frontend have been made

-   [ ] The code has been formatted (`make web`)

If applicable

-   [ ] The documentation has been updated
-   [ ] The documentation has been formatted (`make website`)

### CODE REVIEW

**Comment by BeryJu** [comment]
https://github.com/goauthentik/authentik/commit/5f08485fff05a665b17389f983d8dcfe5ddf5fbc should already fix this, no?

**Comment by jvanbruegge** [comment]
Ah, I did not see that. And it only solves the issue partially. There are still a few packages in `web/package-lock.json` that are missing their integrity (I was already wondering why only so few) and the whole `website/package-lock.json` is missing the fields.

**Comment by jvanbruegge** [comment]
Found why there were a few packages in `web` without integrity, the check only checked for top level depedencies, however you now also have subpackages. The fix is quite easy

**Comment by BeryJu** [comment]
I'm assuming you're using the same method to get the integrity values by `rm -rf node_modules package-lock.json; npm i`?

**Comment by jvanbruegge** [comment]
No, that might change the version of the package. I used this https://github.com/jeslie0/npm-lockfile-fix to only add the integrity and resolved field

**Review by BeryJu — APPROVED** [review]

**Comment by WilliButz** [comment]
@jvanbruegge @BeryJu thank you!

I really don't get why this is not recognized as a problem upstream in npm cli :/

**Pull request merged**
